FROM mcr.microsoft.com/dotnet/sdk:10.0.201 AS build
WORKDIR /source
COPY . .
RUN dotnet restore src/Orbit.Worker/Orbit.Worker.csproj
RUN dotnet publish src/Orbit.Worker/Orbit.Worker.csproj --no-restore -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
USER $APP_UID
ENTRYPOINT ["dotnet", "Orbit.Worker.dll"]
