// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orbit.Infrastructure.Persistence;

#nullable disable

namespace Orbit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrbitDbContext))]
    [Migration("20260813172651_AddSprintsAndMembership")]
    partial class AddSprintsAndMembership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orbit.Domain.Access.ProjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MembershipId");

                    b.HasIndex("TenantId", "ProjectId", "MembershipId")
                        .IsUnique();

                    b.ToTable("project_role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_role_assignments_role", "project_role IN ('Administrator', 'Member', 'Viewer')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Access.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("principal_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tenant_role");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("TenantId", "Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("tenant_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_identity", "(user_id IS NOT NULL AND issuer IS NULL AND subject IS NULL AND principal_type = 'User') OR (user_id IS NULL AND issuer IS NOT NULL AND subject IS NOT NULL)");

                            t.HasCheckConstraint("ck_tenant_memberships_principal_type", "principal_type IN ('User', 'ServiceAccount')");

                            t.HasCheckConstraint("ck_tenant_memberships_role", "tenant_role IN ('Owner', 'Administrator', 'Member')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Board", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "ProjectId");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SprintId", "RemovedAt");

                    b.HasIndex("TenantId", "WorkItemId", "RemovedAt");

                    b.ToTable("sprint_memberships", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Directory.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedByMembershipId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Directory.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MembershipId");

                    b.HasIndex("TenantId", "TeamId", "MembershipId")
                        .IsUnique();

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Identity.LocalCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<int>("HashParametersVersion")
                        .HasColumnType("integer")
                        .HasColumnName("hash_parameters_version");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId");

                    b.ToTable("local_credentials", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("refresh_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_status", "status IN ('Active', 'Rotated', 'Revoked')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Identity.SiteRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("site_role");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("UserId", "Role");

                    b.ToTable("site_role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_site_role_assignments_role", "site_role = 'SuperAdministrator'");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("user_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("NextItemSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_item_sequence");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_key", "key ~ '^[A-Z0-9]{2,10}$'");

                            t.HasCheckConstraint("ck_projects_next_sequence", "next_item_sequence > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Settings.NotificationPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DigestCadence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("digest_cadence");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_enabled");

                    b.Property<bool>("InAppEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("in_app_enabled");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_start");

                    b.Property<bool>("SelfNotify")
                        .HasColumnType("boolean")
                        .HasColumnName("self_notify");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Settings.ProjectSetting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("default_priority");

                    b.Property<string>("DefaultWorkItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_work_item_type");

                    b.Property<bool>("EnableReleases")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_releases");

                    b.Property<bool>("EnableTimeTracking")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_time_tracking");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "ProjectId");

                    b.ToTable("project_settings", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Settings.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("density");

                    b.Property<bool>("HighContrast")
                        .HasColumnType("boolean")
                        .HasColumnName("high_contrast");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<bool>("ReduceMotion")
                        .HasColumnType("boolean")
                        .HasColumnName("reduce_motion");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("theme");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Settings.WorkspaceSetting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("AllowMemberProjectCreation")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_member_project_creation");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("default_locale");

                    b.Property<string>("DefaultTimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_time_zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId");

                    b.ToTable("workspace_settings", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)")
                        .HasColumnName("acceptance_criteria");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.PrimitiveCollection<string[]>("AttachmentNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("attachment_names");

                    b.PrimitiveCollection<string[]>("Countries")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("countries");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DeveloperUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("developer_user_id");

                    b.Property<string>("EpicName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("epic_name");

                    b.Property<string>("IdentifiedOn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("identified_on");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.PrimitiveCollection<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<string>("LinkType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("link_type");

                    b.Property<Guid?>("LinkedWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_work_item_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProductOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_owner_user_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("Rank")
                        .HasPrecision(38, 16)
                        .HasColumnType("numeric(38,16)")
                        .HasColumnName("rank");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SprintName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sprint_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StepsToConduct")
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)")
                        .HasColumnName("steps_to_conduct");

                    b.Property<decimal?>("StoryPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("story_points");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.HasIndex("TenantId", "LinkedWorkItemId");

                    b.HasIndex("TenantId", "ParentId");

                    b.HasIndex("TenantId", "ProjectId", "Status", "Rank");

                    b.ToTable("work_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_items_epic_name", "type <> 'Epic' OR epic_name IS NOT NULL");

                            t.HasCheckConstraint("ck_work_items_link", "(link_type IS NULL) = (linked_work_item_id IS NULL)");

                            t.HasCheckConstraint("ck_work_items_link_type", "link_type IS NULL OR link_type IN ('DependsOn', 'Blocks', 'RelatesTo')");

                            t.HasCheckConstraint("ck_work_items_priority", "priority IN ('Lowest', 'Low', 'Medium', 'High', 'Highest')");

                            t.HasCheckConstraint("ck_work_items_sequence", "sequence_number > 0");

                            t.HasCheckConstraint("ck_work_items_status", "status IN ('Backlog', 'Selected', 'InProgress', 'InReview', 'Done', 'Blocked')");

                            t.HasCheckConstraint("ck_work_items_story_points", "story_points IS NULL OR story_points BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_work_items_type", "type IN ('Initiative', 'Epic', 'Task', 'Story', 'Spike', 'Test', 'Feature', 'Request', 'Bug', 'Subtask')");

                            t.HasCheckConstraint("ck_work_items_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AuthorizationEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("authorization_epoch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("workspaces", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspaces_authorization_epoch", "authorization_epoch > 0");

                            t.HasCheckConstraint("ck_workspaces_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Access.ProjectRoleAssignment", b =>
                {
                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Access.TenantMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Board", b =>
                {
                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Boards.Board", "TenantId", "ProjectId")
                        .HasPrincipalKey("Orbit.Domain.Projects.Project", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Orbit.Domain.Boards.BoardColumn", "Columns", b1 =>
                        {
                            b1.Property<Guid>("tenant_id")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("project_id")
                                .HasColumnType("uuid")
                                .HasColumnName("project_id");

                            b1.Property<string>("Status")
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<int?>("WipLimit")
                                .HasColumnType("integer")
                                .HasColumnName("wip_limit");

                            b1.Property<string>("WipLimitMode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("wip_limit_mode");

                            b1.HasKey("tenant_id", "project_id", "Status");

                            b1.ToTable("board_columns", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("tenant_id", "project_id");
                        });

                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Sprint", b =>
                {
                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Boards.Sprint", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SprintId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Directory.Team", b =>
                {
                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedByMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Directory.TeamMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TeamId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.LocalCredential", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Identity.LocalCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.SiteRoleAssignment", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.NotificationPreference", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.NotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.ProjectSetting", b =>
                {
                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.ProjectSetting", "TenantId", "ProjectId")
                        .HasPrincipalKey("Orbit.Domain.Projects.Project", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.UserPreference", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.WorkspaceSetting", b =>
                {
                    b.HasOne("Orbit.Domain.Workspaces.Workspace", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.WorkspaceSetting", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItem", b =>
                {
                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LinkedWorkItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ParentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
