// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orbit.Infrastructure.Persistence;

#nullable disable

namespace Orbit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrbitDbContext))]
    partial class OrbitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orbit.Domain.Access.ProjectGroupRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "GroupId");

                    b.HasIndex("TenantId", "ProjectId", "GroupId")
                        .IsUnique();

                    b.ToTable("project_group_role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_group_role_assignments_role", "project_role IN ('Administrator', 'Member', 'Viewer')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Access.ProjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MembershipId");

                    b.HasIndex("TenantId", "ProjectId", "MembershipId")
                        .IsUnique();

                    b.ToTable("project_role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_role_assignments_role", "project_role IN ('Administrator', 'Member', 'Viewer')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Access.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("principal_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tenant_role");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("TenantId", "Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("tenant_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_guest_role", "tier <> 'Guest' OR tenant_role = 'Member'");

                            t.HasCheckConstraint("ck_tenant_memberships_identity", "(user_id IS NOT NULL AND issuer IS NULL AND subject IS NULL AND principal_type = 'User') OR (user_id IS NULL AND issuer IS NOT NULL AND subject IS NOT NULL)");

                            t.HasCheckConstraint("ck_tenant_memberships_principal_type", "principal_type IN ('User', 'ServiceAccount')");

                            t.HasCheckConstraint("ck_tenant_memberships_role", "tenant_role IN ('Owner', 'Administrator', 'Member')");

                            t.HasCheckConstraint("ck_tenant_memberships_tier", "tier IN ('Standard', 'Guest')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Access.WorkspaceInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_membership_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tenant_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "InvitedByMembershipId");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasFilter("status = 'Active'");

                    b.HasIndex("TenantId", "TeamId");

                    b.ToTable("workspace_invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_invitations_guest_role", "tier <> 'Guest' OR tenant_role = 'Member'");

                            t.HasCheckConstraint("ck_workspace_invitations_role", "tenant_role IN ('Administrator', 'Member')");

                            t.HasCheckConstraint("ck_workspace_invitations_status", "status IN ('Active', 'Accepted', 'Revoked')");

                            t.HasCheckConstraint("ck_workspace_invitations_tier", "tier IN ('Standard', 'Guest')");

                            t.HasCheckConstraint("ck_workspace_invitations_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Board", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "ProjectId");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintCompletionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_count");

                    b.Property<Guid?>("RolloverTargetSprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("rollover_target_sprint_id");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SprintId")
                        .IsUnique();

                    b.ToTable("sprint_completion_operations", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SprintId", "RemovedAt");

                    b.HasIndex("TenantId", "WorkItemId", "RemovedAt");

                    b.ToTable("sprint_memberships", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintScopeFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("EstimateDelta")
                        .HasColumnType("numeric")
                        .HasColumnName("estimate_delta");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fact_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SprintId", "OccurredAt", "Id");

                    b.ToTable("sprint_scope_facts", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Configuration.CustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.HasIndex("TenantId", "Order");

                    b.ToTable("custom_field_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_field_definitions_order", "\"order\" BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_custom_field_definitions_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Configuration.WorkItemTypeDefinition", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("ColorToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color_token");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Order");

                    b.ToTable("work_item_type_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_item_type_definitions_order", "\"order\" BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_work_item_type_definitions_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Directory.DirectoryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedByMembershipId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("directory_groups", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Directory.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MembershipId");

                    b.HasIndex("TenantId", "GroupId", "MembershipId")
                        .IsUnique();

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Directory.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedByMembershipId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Directory.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MembershipId");

                    b.HasIndex("TenantId", "TeamId", "MembershipId")
                        .IsUnique();

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Identity.GoogleSignInHandoff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("google_sign_in_handoffs", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Identity.LocalCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<int>("HashParametersVersion")
                        .HasColumnType("integer")
                        .HasColumnName("hash_parameters_version");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId");

                    b.ToTable("local_credentials", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("password_reset_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_password_reset_tokens_status", "status IN ('Active', 'Used', 'Revoked')");

                            t.HasCheckConstraint("ck_password_reset_tokens_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_persistent");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("refresh_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_status", "status IN ('Active', 'Rotated', 'Revoked')");

                            t.HasCheckConstraint("ck_refresh_sessions_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Identity.ServiceAccountCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "RevokedAt");

                    b.HasIndex("MembershipId", "RevokedAt");

                    b.ToTable("service_account_credentials", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Identity.SiteRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("site_role");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("UserId", "Role");

                    b.ToTable("site_role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_site_role_assignments_role", "site_role = 'SuperAdministrator'");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("user_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Messaging.OutboxEmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FrontendBaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("frontend_base_url");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("subject");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("to_email");

                    b.Property<Guid?>("WorkspaceInvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_invitation_id");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "Attempts", "CreatedAt");

                    b.ToTable("outbox_email_messages", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("organization_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_organization_memberships_role", "role IN ('Owner', 'Administrator', 'Member')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("NextItemSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_item_sequence");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_key", "key ~ '^[A-Z0-9]{2,10}$'");

                            t.HasCheckConstraint("ck_projects_next_sequence", "next_item_sequence > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Settings.NotificationPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DigestCadence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("digest_cadence");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_enabled");

                    b.Property<bool>("InAppEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("in_app_enabled");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_start");

                    b.Property<bool>("SelfNotify")
                        .HasColumnType("boolean")
                        .HasColumnName("self_notify");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Settings.ProjectSetting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("default_priority");

                    b.Property<string>("DefaultWorkItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_work_item_type");

                    b.Property<bool>("EnableReleases")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_releases");

                    b.Property<bool>("EnableTimeTracking")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_time_tracking");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "ProjectId");

                    b.HasIndex("TenantId", "DefaultWorkItemType");

                    b.ToTable("project_settings", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Settings.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("density");

                    b.Property<bool>("HighContrast")
                        .HasColumnType("boolean")
                        .HasColumnName("high_contrast");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<bool>("ReduceMotion")
                        .HasColumnType("boolean")
                        .HasColumnName("reduce_motion");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("theme");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Settings.WorkspaceSetting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("AllowMemberProjectCreation")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_member_project_creation");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("default_locale");

                    b.Property<string>("DefaultTimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_time_zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("LogoObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("logo_object_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId");

                    b.ToTable("workspace_settings", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.Settings.WorkspaceTypographySetting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ControlFontSizePx")
                        .HasColumnType("integer")
                        .HasColumnName("control_font_size_px");

                    b.Property<int>("ControlHeightPx")
                        .HasColumnType("integer")
                        .HasColumnName("control_height_px");

                    b.Property<string>("LeftFontColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("left_font_color");

                    b.Property<string>("LeftFontFamily")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("left_font_family");

                    b.Property<int>("LeftFontSizePx")
                        .HasColumnType("integer")
                        .HasColumnName("left_font_size_px");

                    b.Property<string>("MiddleFontColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("middle_font_color");

                    b.Property<string>("MiddleFontFamily")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("middle_font_family");

                    b.Property<int>("MiddleFontSizePx")
                        .HasColumnType("integer")
                        .HasColumnName("middle_font_size_px");

                    b.Property<string>("RightFontColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("right_font_color");

                    b.Property<string>("RightFontFamily")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("right_font_family");

                    b.Property<int>("RightFontSizePx")
                        .HasColumnType("integer")
                        .HasColumnName("right_font_size_px");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId");

                    b.ToTable("workspace_typography_settings", (string)null);
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_membership_id");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_attachments_object_key");

                    b.HasIndex("TenantId", "WorkItemId", "Id")
                        .HasDatabaseName("ix_attachments_tenant_item_id");

                    b.HasIndex("TenantId", "WorkItemId", "UploadedAt")
                        .HasDatabaseName("ix_attachments_tenant_item_uploaded");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_size_bytes", "size_bytes > 0 AND size_bytes <= 26214400");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)")
                        .HasColumnName("acceptance_criteria");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.PrimitiveCollection<string[]>("AttachmentNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("attachment_names");

                    b.PrimitiveCollection<string[]>("Countries")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("countries");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DeveloperUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("developer_user_id");

                    b.Property<string>("EpicName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("epic_name");

                    b.Property<string>("IdentifiedOn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("identified_on");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.PrimitiveCollection<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProductOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_owner_user_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("Rank")
                        .HasPrecision(38, 16)
                        .HasColumnType("numeric(38,16)")
                        .HasColumnName("rank");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SprintName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sprint_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StepsToConduct")
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)")
                        .HasColumnName("steps_to_conduct");

                    b.Property<decimal?>("StoryPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("story_points");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.HasIndex("TenantId", "ParentId");

                    b.HasIndex("TenantId", "Type");

                    b.HasIndex("TenantId", "ProjectId", "Status", "Rank");

                    b.ToTable("work_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_items_epic_name", "type <> 'Epic' OR epic_name IS NOT NULL");

                            t.HasCheckConstraint("ck_work_items_priority", "priority IN ('Lowest', 'Low', 'Medium', 'High', 'Highest')");

                            t.HasCheckConstraint("ck_work_items_sequence", "sequence_number > 0");

                            t.HasCheckConstraint("ck_work_items_status", "status IN ('Backlog', 'Selected', 'InProgress', 'InReview', 'Done', 'Blocked')");

                            t.HasCheckConstraint("ck_work_items_story_points", "story_points IS NULL OR story_points BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_work_items_type", "type IN ('Initiative', 'Epic', 'Task', 'Story', 'Spike', 'Test', 'Feature', 'Request', 'Bug', 'Subtask')");

                            t.HasCheckConstraint("ck_work_items_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_membership_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("LastEditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_at");

                    b.PrimitiveCollection<Guid[]>("MentionedUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("mentioned_user_ids");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WorkItemId", "CreatedAt")
                        .HasDatabaseName("ix_work_item_comments_tenant_item_created");

                    b.HasIndex("TenantId", "WorkItemId", "Id")
                        .HasDatabaseName("ix_work_item_comments_tenant_item_id");

                    b.ToTable("work_item_comments", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_item_comments_body_length", "char_length(body) BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("ck_work_item_comments_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItemLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("SourceWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_work_item_id");

                    b.Property<Guid>("TargetWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_work_item_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceWorkItemId");

                    b.HasIndex("TenantId", "TargetWorkItemId");

                    b.HasIndex("TenantId", "SourceWorkItemId", "TargetWorkItemId", "Kind")
                        .IsUnique();

                    b.ToTable("work_item_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_item_links_distinct", "source_work_item_id <> target_work_item_id");

                            t.HasCheckConstraint("ck_work_item_links_kind", "kind IN ('Blocks', 'RelatesTo', 'Duplicates')");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AuthorizationEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("authorization_epoch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("workspaces", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspaces_authorization_epoch", "authorization_epoch > 0");

                            t.HasCheckConstraint("ck_workspaces_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Orbit.Domain.Access.ProjectGroupRoleAssignment", b =>
                {
                    b.HasOne("Orbit.Domain.Directory.DirectoryGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "GroupId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Access.ProjectRoleAssignment", b =>
                {
                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Access.TenantMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Orbit.Domain.Access.WorkspaceInvitation", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "InvitedByMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TeamId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Board", b =>
                {
                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Boards.Board", "TenantId", "ProjectId")
                        .HasPrincipalKey("Orbit.Domain.Projects.Project", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Orbit.Domain.Boards.BoardColumn", "Columns", b1 =>
                        {
                            b1.Property<Guid>("tenant_id")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("project_id")
                                .HasColumnType("uuid")
                                .HasColumnName("project_id");

                            b1.Property<string>("Status")
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<int?>("WipLimit")
                                .HasColumnType("integer")
                                .HasColumnName("wip_limit");

                            b1.Property<string>("WipLimitMode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("wip_limit_mode");

                            b1.HasKey("tenant_id", "project_id", "Status");

                            b1.ToTable("board_columns", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("tenant_id", "project_id");
                        });

                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Orbit.Domain.Boards.Sprint", b =>
                {
                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintCompletionOperation", b =>
                {
                    b.HasOne("Orbit.Domain.Boards.Sprint", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SprintId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Boards.Sprint", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SprintId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Boards.SprintScopeFact", b =>
                {
                    b.HasOne("Orbit.Domain.Boards.Sprint", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SprintId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Directory.DirectoryGroup", b =>
                {
                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedByMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Directory.GroupMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Directory.DirectoryGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "GroupId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Directory.Team", b =>
                {
                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedByMembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Directory.TeamMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Access.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MembershipId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TeamId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.GoogleSignInHandoff", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.LocalCredential", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Identity.LocalCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Identity.SiteRoleAssignment", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("Orbit.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.NotificationPreference", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.NotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.ProjectSetting", b =>
                {
                    b.HasOne("Orbit.Domain.Configuration.WorkItemTypeDefinition", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DefaultWorkItemType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.ProjectSetting", "TenantId", "ProjectId")
                        .HasPrincipalKey("Orbit.Domain.Projects.Project", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.UserPreference", b =>
                {
                    b.HasOne("Orbit.Domain.Identity.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.WorkspaceSetting", b =>
                {
                    b.HasOne("Orbit.Domain.Workspaces.Workspace", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.WorkspaceSetting", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Settings.WorkspaceTypographySetting", b =>
                {
                    b.HasOne("Orbit.Domain.Workspaces.Workspace", null)
                        .WithOne()
                        .HasForeignKey("Orbit.Domain.Settings.WorkspaceTypographySetting", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.Attachment", b =>
                {
                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItem", b =>
                {
                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ParentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbit.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.Configuration.WorkItemTypeDefinition", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItemComment", b =>
                {
                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "WorkItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.WorkItems.WorkItemLink", b =>
                {
                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourceWorkItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbit.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TargetWorkItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit.Domain.Workspaces.Workspace", b =>
                {
                    b.HasOne("Orbit.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
